
name: Github Action Demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test with Maven  # Chạy test
        run: mvn test && mvn package
      - name: Build Jar file
        run: mkdir staging && cp target/*.jar staging  # Đưa file jar vào artifact Github
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging